import InfluencerImg from "../../Assets/InfluencerImg.png";
import Instagram from "../../Assets/Instagram.svg";
import FaceBook from "../../Assets/Facebook.svg";
import YouTube from "../../Assets/YouTube.svg";

const influencersData = [
  {
    id: 1,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 2,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 3,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 4,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 5,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 6,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 7,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 8,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 9,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 10,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 11,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
  {
    id: 12,
    name: "Gautam Sachdeva",
    verified: true,
    img: InfluencerImg,
    star: [1, 2, 3, 4],
    review: "30 reviews",
    platforms: [
      { name: "Instagram", img: Instagram },
      { name: "Facebook", img: FaceBook },
      { name: "Youtube", img: YouTube },
    ],
    liked: false,
    button: "Invite",
  },
];

const listItem = [
  { name: "Favorites", influencers: [6, 7, 8, 9, 10, 11, 12] },
  { name: "Work", influencers: [10, 11, 12] },
  { name: "Travel", influencers: [4, 5, 6] },
  { name: "Fashion", influencers: [7, 8, 9] },
];

export { listItem, influencersData };
